config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :authorizations, only: %i[new create]

  concern :votable do
    member  do
      patch 'vote_up'
      patch 'vote_down'
      delete 'delete_vote'
    end
  end

  concern :commentable do
    member do
      post 'create_comment'
      delete 'delete_comment'
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      member do
        patch 'set_best'
      end
    end
    resources :subscriptions, only: :create do
      delete :destroy, on: :collection
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions, only: %i[show index create] do
        resources :answers, only: %i[show index create]
      end
    end
  end

  resources :search, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

  belongs_to :user

  validates :title, :body, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: proc { |a| a[:file].blank? }, allow_destroy: true

  after_create :update_reputation, :autosubscribe_for_own

  def to_s
    self[:title]
  end

  private

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end

  def autosubscribe_for_own
    user.subscribe!(id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: :show

  authorize_resource :question

  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionArraySerializer
  end

  def show
    respond_with @question
  end

  def create
    @question = Question.new(questions_params)
    @question.user_id = current_user.id
    @question.save

    respond_with @question
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :load_owner, only: [:destroy]
  before_action :build_answer, only: :show

  after_action :publish_question, only: [:create]

  respond_to :html

  authorize_resource

  include Voted

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
    respond_with @question
  end

  def create
    @question = Question.new(questions_params)
    @question.user_id = current_user.id
    @question.save

    respond_with @question
  end

  def update
    @question.update(questions_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('questions', locals: { question: @question.to_json })
  end

  private

  def load_question
    @question = Question.find_by(id: params[:id])
  end

  def load_owner
    return redirect_to @question if @question.user != current_user
  end

  def questions_params
    params.require(:question).permit(:title, :body, attachments_attributes: %i[id file _destroy])
  end

  def build_answer
    @answer = @question.answers.build
    @comment = Comment.new
  end
end

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  - if answer.persisted?
    == render 'answers/answer', answer: answer

app/views/questions/_attachment_fields.html.slim
.nested-fields id="#{dom_id(f.object)}"
  - if f.object.new_record?
    p = f.label :file
    p = f.file_field :file
  - else
    p = f.object.file.identifier
    p = link_to_remove_association 'remove attach', f

app/views/questions/_new_answer.html.slim
= form_for [@question, @answer], remote: true do |f|
  h4 = f.label :body, 'Your answer'
  .answer-errors
  p = f.text_area :body
  = f.fields_for :attachments, @answer.attachments.build do |a|
    == render 'attachment_fields', f: a
  .links
    p = link_to_add_association 'add file', f, :attachments 
  p = f.submit 'Create'

app/views/questions/_question.html.slim
tr
  td
    = link_to question, question_path(question)
  td
    = question.body
  td
    - if can?(:edit, Question) && question.user_id == current_user.id
        = link_to 'Edit', edit_question_path(question), class: 'btn btn-sm btn-warning'
        = link_to 'Delete', question_path(question), method: :delete, class: 'btn btn-sm btn-danger'

app/views/questions/_question_form.html.slim
p = f.label :title
p = f.text_field :title
p = f.label :body, 'Your question'
p = f.text_area :body

app/views/questions/_subscription.html.slim
.subscription
  -if current_user.subscribed?(question)
    = link_to 'Unsubscribe', question_subscriptions_path(question), method: :delete, remote: true
  - else
    = link_to 'Subscribe', question_subscriptions_path(question), method: :post, remote: true

app/views/questions/_vote.html.slim
.vote
  div class="raiting-Question#{question.id}"
    | Raiting: 
    = question.total_score
  .vote_contol
    - if signed_in? && question.user_id != current_user.id
      = button_to 'up', vote_up_question_path(question), id: "voteup-Question#{question.id}", disabled: voted, method: :patch, remote: true
      = button_to 'down', vote_down_question_path(question), id: "votedown-Question#{question.id}", disabled: voted, method: :patch, remote: true
      = button_to 'clean', delete_vote_question_path(question), id: "voteclean-Question#{question.id}", disabled: !voted, method: :delete, remote: true

app/views/questions/edit.html.slim
= form_for @question do |f|
  == render 'question_form', f: f
  p Attachments:
  p 
    = f.fields_for :attachments do |a|
      == render 'attachment_fields', f: a
  .links
    = link_to_add_association 'add file', f, :attachments 
  p = f.submit
   

app/views/questions/index.html.slim
= form_with(url: '/search', method: 'get', class: 'search') do |f|
  = f.text_area :content, type: 'search', placeholder: 'Search'
  div class='search-select'
    = f.select :context, options_for_select(Search::FILTER, params[:context])
    = f.submit 'Search', class: 'btn btn-sm btn-primary search-button'

- if can?(:create, Question)
  = link_to 'Ask Question', new_question_path, class: "btn btn-success"

- unless user_signed_in?
  div class="btn-group"
    = link_to 'Login', new_user_session_path, class: "btn btn-primary"
    = link_to 'Register', new_user_registration_path, class: "btn btn-warning"

label class="label-list-questions" List of all questions:

table class='datatable'
  thead
    tr
      th
        | Title
      th
        | Question
      th
  tbody
    - @questions.each do |question|
      == render "question", question: question

app/views/questions/new.html.slim
= form_for @question do |f|
  == render 'question_form', f: f
  p Attachments:
  p 
    = f.fields_for :attachments, @question.attachments.build  do |a|
      == render 'attachment_fields', f: a
  .links
    = link_to_add_association 'add file', f, :attachments 
  p = f.submit 'Create'

app/views/questions/show.html.slim
h2 = @question.title
p = @question.body
== render 'vote', question: @question, voted: @question.voted_by?(current_user)
- if current_user
  == render 'subscription', question: @question
h3 Attachments:
ul
  - @question.attachments.each do |a|
    li = link_to a.file.identifier, a.file.url
- if user_signed_in? && @question.user_id == current_user.id
  div class='btn-group'
    = link_to 'Edit', edit_question_path(@question), class: 'btn btn-sm btn-warning'
    = link_to 'Delete question', question_path(@question), method: :delete, class: 'btn btn-sm btn-danger'
.comments_show_question style='float: right'
  .comments_Question
    .Question-comments id="#{@question.id}"
      h3 Comments for question:
      == render @question.comments.order('created_at')
  .question-comment-form
      == render 'comments/form', commentable: @question

h3 All answers for this questions
.answers
  == render 'answers'

== render 'new_answer'