config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :authorizations, only: %i[new create]

  concern :votable do
    member  do
      patch 'vote_up'
      patch 'vote_down'
      delete 'delete_vote'
    end
  end

  concern :commentable do
    member do
      post 'create_comment'
      delete 'delete_comment'
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      member do
        patch 'set_best'
      end
    end
    resources :subscriptions, only: :create do
      delete :destroy, on: :collection
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions, only: %i[show index create] do
        resources :answers, only: %i[show index create]
      end
    end
  end

  resources :search, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachmentable, dependent: :destroy

  validates :body, :question_id, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: proc { |a| a[:file].blank? }, allow_destroy: true

  default_scope { order(best: :desc) }

  after_create :update_reputation

  after_commit :notify_users

  def set_best!
    old_best_answer = question.answers.find_by(best: true)
    return if old_best_answer == self

    old_best_answer&.update!(best: false)
    update!(best: true)
  end

  private

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end

  def notify_users
    users = question.users
    users.each do |user|
      NotifyMailer.added_answer(user, self).deliver_later
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: %i[new create destroy]
  before_action :load_answer, only: %i[update set_best]

  after_action :publish_question, only: [:create]

  authorize_resource

  respond_to :js
  respond_to :json, only: :create

  include Voted

  def new
    respond_with(@answer = @question.answers.new)
  end

  def create
    @answer = @question.answers.create(answers_params)
    @answer.user_id = current_user.id
    @answer.save
    respond_with @answer
  end

  def update
    @answer.update(answers_params)
    respond_with @answer
  end

  def destroy
    @answer.destroy
  end

  def set_best
    @answer.set_best! if @question.user == current_user
  end

  def publish_question
    return if @answer.errors.any?

    ActionCable.server.broadcast('answers', locals: { answer: @answer.to_json })
  end

  private

  def load_question
    @question = Question.find_by(id: params[:question_id])
  end

  def load_answer
    @answer = Answer.find_by(id: params[:id])
    @question = @answer.question
  end

  def answers_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: %i[index create]
  before_action :load_answer, only: [:show]

  authorize_resource :answer

  def index
    @answers = @question.answers
    respond_with @answers, each_serializer: AnswerArraySerializer
  end

  def show
    respond_with @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner
    @answer.save
    respond_with(@answer)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
div id="answer-#{ answer.id }" style='margin-top: 20px'
  -if answer.best
    h4 = 'Best answer: '
  p = answer.body
  == render 'answers/vote', answer: answer, voted: answer.voted_by?(current_user)
  ul
    - answer.attachments.each do |a|
      li = link_to a.file.identifier, a.file.url

  .comments_Answer
    .Answer-comments id="#{answer.id}"
      == render answer.comments.order('created_at')
  .answer-comment-form
      == render 'comments/form', commentable: answer

  - if user_signed_in? && answer.user_id == current_user.id
    div class="btn-group"
      = link_to 'Best', set_best_answer_path(answer), method: :patch, remote: true, class: 'btn btn-sm btn-primary'
      = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }, class: 'btn btn-sm btn-warning'
      = link_to 'Delete', answer_path(answer), method: :delete, remote: true, class: 'btn btn-sm btn-danger'
    
    = form_for answer, remote: true, html: { id: "edit-answer-#{ answer.id }" } do |f|
      = f.label :body, 'Edit answer'
      p = f.text_area :body
      = f.fields_for :attachments do |a|
        == render 'questions/attachment_fields', f: a
    	.links
        = link_to_add_association 'Add attachment', f, :attachments, partial: 'questions/attachment_fields'
      p = f.submit 'Save'

app/views/answers/_vote.html.slim
.vote
  div class="raiting-Answer#{answer.id}"
    | Raiting: 
    = answer.total_score
  .vote_contol
    - if signed_in? && answer.user_id != current_user.id
      = button_to 'up', vote_up_answer_path(answer), id: "voteup-Answer#{answer.id}", disabled: voted, method: :patch, remote: true
      = button_to 'down', vote_down_answer_path(answer), id: "votedown-Answer#{answer.id}", disabled: voted, method: :patch, remote: true
      = button_to 'clean', delete_vote_answer_path(answer), id: "voteclean-Answer#{answer.id}", disabled: !voted, method: :delete, remote: true

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render "questions/answers", answer: @answer, comment: @comment %>');
  $('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  <% if @answer.destroyed? %>
    $('<%= "#answer-#{@answer.id}" %>').remove();
  <% end %>
<% end %>

app/views/answers/set_best.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render "questions/answers" %>');
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('<%= "#answer-#{ @answer.id }" %>').replaceWith('<%= j render "answer", answer: @answer, comment: @comment %>');
  $('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId')
    $('form#edit-answer-' + answer_id).show()
  });
<% end %>